### ISSUE TITLE
Interface does not show up in RoboFont 4.4

### ISSUE THREAD

**Issue by ninastoessinger** [jansindl3r/Scale-absolutely#5]
Hi! Thanks for making ScaleAbsolutely, really enjoying it and it’s very useful!
Unfortunately after upgrading to RoboFont 4.4 (using v.0.51 of ScaleAbsolutely), the ScaleAbsolutely interface does not appear in the Inspector. When opening the Inspector window I get this error message in the Output Window:
```
Observer '<__main__.ScaleAbsolutely object at 0x11cad7b20>' with 'inspectorWindowWillShowDescriptions' failed: 'view'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 570, in openInspector_
AttributeError: 'DoodleAppDelegate' object has no attribute '_inspectorWindow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 165, in callObserver_withMethod_forEvent_withInfo_
  File "scaleAbsolutely.py", line 227, in inspectorWindowWillShowDescriptions
KeyError: 'view'
```
Any ideas?

**Comment by jansindl3r** [comment]
Hi Nina, 

thanks a lot for reporting it and letting me know that you like using it! 

I am looking into it and indeed, it stopped working in the latest RoboFont 4.4

**Comment by ninastoessinger** [comment]
Great, thanks for looking into it! Also Tobias and Fred asked me to pass along their thanks as well for making Scale Absolutely, we all work with it and enjoy it a lot :)

**Comment by jansindl3r** [comment]
Hi Nina, thanks again for the support! 

I have fixed it, i was recommended by Frederik to follow more standard conventions, so I added a separate tab for this extension. It's a bit unfortunate it won't be placed next to the default transform, but it's in the tab right above, so I hope that's fine. I hope it's all fine now and sorry it took a bit longer to fix.

Best, Jan
